config/routes.rb
Rails.application.routes.draw do
  resources :gossips do
    resources :like, only: [:index, :create, :destroy]
  end
  resources :gossips do
    resources :comments
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :authors, only: [:show, :create, :new]
  resources :cities, only: [:show]
  resources :team, only: [:index]
  resources :contact, only: [:index]
  resources :welcome, only: [:index, :show]
  root to: 'gossips#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	validates :name,
	  presence: true,
	  uniqueness: true #une ville n'a pas le meme nom en fr
	validates :zip_code,
	  presence: true,
	  format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "please enter a valid french zip code" } 
	has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
	validates :content,
	  presence: true
	belongs_to :user		#Comment en relation N-1 avec user et gossip 
	belongs_to :gossip
	
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	validates :title, 
	  presence: true,
	  length: { in: 3..14, wrong_length: "3 to 14 characters is allowed" }
	validates :content,
	  presence: true,
	  length: { minimum: 50, too_short: "50 characters is the minimum allowed" }
	
	belongs_to :user
	has_many :comments
	has_many :join_tag_gossips
	has_many :tags, through: :join_tag_gossips
	has_many :likes

end

app/models/join_pm.rb
class JoinPm < ApplicationRecord
	validates :user_id,
	    presence: true,
	    numericality: { only_integer: true, greater_than_or_equal_to: 1}
	validates :private_message_id,
	    presence: true,
	    numericality: { only_integer: true, greater_than_or_equal_to: 1}
	    
	belongs_to :user
	belongs_to :private_message
end

app/models/join_tag_gossip.rb
class JoinTagGossip < ApplicationRecord
	validates :tag_id,
	    presence: true,
	    numericality: { only_integer: true, greater_than_or_equal_to: 1}
	validates :gossip_id,
	    presence: true,
	    numericality: { only_integer: true, greater_than_or_equal_to: 1}
	belongs_to :tag 
	belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
	validate :unique_like

	belongs_to :user
	belongs_to :gossip

	def unique_like
		if User.find(user_id).unique(gossip_id)
			errors.add(:gossip_id, "déjà fait") 
		end
	end
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	  validates :content,
	    presence: true
	  
	  belongs_to :user
	  has_many :join_pms
	  has_many :users, through: :join_pms
      
end

app/models/tag.rb
class Tag < ApplicationRecord
	validates :title, 
	  presence: true,
	  length: { in: 3..14, wrong_length: "3 to 14 characters is allowed" }
	  
	has_many :join_tag_gossips
	has_many :gossips, through: :join_tag_gossips
end

app/models/user.rb
class User < ApplicationRecord
	validates :email,
      presence: true, #tjr rempli
      uniqueness: true,  #unique
      format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" } #format
    validates :first_name,
      presence: true
    validates :last_name,
      presence: true
    validates :description,
      presence: true,
      length: { minimum: 50, too_short: "50 characters is the minimum allowed" }
    validates :age,
      presence: true,
      numericality: { only_integer: true, greater_than_or_equal_to: 1}
    validates :password, 
      presence: true, 
      length: { minimum: 6 }
      
    has_secure_password
	belongs_to :city
	has_many :gossips
	has_many :private_messages
	has_many :join_pms
	has_many :likes
 
 	def unique(gsp_id)
 		
 		self.likes.map{|like| like.gossip_id}.include?(gsp_id)
 		
 	end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
    before_action :authenticate_user, except: [:show, :index]
    before_action :authenticate_current_user, only: [:edit, :update, :destroy]

  def index
  end

  def show
  	@gossip = Gossip.find(params[:id].to_i)
  	@comments = Comment.all.to_a
  end

  def new
  end

  def create
  	@gossip = Gossip.new(title: params[:gossip_title],content: params[:gossip_content]) 
  	@gossip.user = current_user
  	if @gossip.save # essaie de sauvegarder en base @gossip
    	flash.now[:success] = 'Bravo tu as bien enregistré ton Gossip !'
    	render :index
    else
    	flash.now[:alert] = "Loupé ! un titre, un contenu et c'est parti!"
    	render :new
    end
  end

  def edit
  	@gossip = Gossip.find(params[:id].to_i)
  end

  def update
  	@gossip = Gossip.find(params[:id].to_i)
  	post_params = params.require(:gossip).permit(:title, :content)
   	if @gossip.update(title: post_params[:title],content: post_params[:content],user_id: @gossip.user_id)
  		redirect_to @gossip
  	else
  		flash.now[:alert] = "Loupé !"
  		render :edit
  	end
  end

  def destroy
  	@gossip = Gossip.find(params[:id].to_i)
  	@gossip.destroy
  	render :index
  end

   private

  def authenticate_user
    unless current_user
      flash[:alert] = "Please log in."
      redirect_to new_session_path
    end
  end

  def authenticate_current_user
    @gossip = Gossip.find(params[:id].to_i)
    unless current_user.id == @gossip.user_id
    	redirect_to gossips_path
  	end
  end

end

app/controllers/like_controller.rb
class LikeController < ApplicationController
	before_action :get_gossip
	before_action :authenticate_user

	def index
		@likes= @gossip.likes
	end

	def create
		@like = @gossip.likes.new(gossip_id: params[:gossip_id])
		@like.user = current_user 
  		@like.save
  		redirect_to gossip_path(@gossip)
	end

	def destroy
		@gossip = Gossip.find(params[:gossip_id].to_i) #pourquoi ca ne reprend pas la fct private..
  		@like = @gossip.likes.find(params[:id].to_i)
  		@like.destroy
  		redirect_to gossip_path(@gossip), notice: 'Le like a été supprimé.'
	end

	private

 		def get_gossip
    		@gossip = Gossip.find(params[:gossip_id].to_i)
  		end

  		def authenticate_user
    		unless current_user
      		flash[:alert] = "Please log in."
      		redirect_to new_session_path
    	end
  end

end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_class_for flash_type
        { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }.stringify_keys[flash_type.to_s] || flash_type.to_s
    end
    
    def flash_messages(opts = {})
        flash.each do |msg_type, message|
          concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}", role: "alert") do 
                  concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
                  concat message 
                end)
        end
        nil
    end

    def current_user
    	User.find_by(id: session[:user_id])
	end

	def log_in(user)
    	session[:user_id] = user.id
  	end

  	def logged_in?
  		session[:user_id]
  	end

end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
    	session[:user_id] = user.id
  	end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossips/edit.html.erb
<html>
  <body>
    <div class="container">
      <%= flash_messages %> <!-- voir applicaiton helper-->
      <%= yield %>
    </div>

    <div class="container">
      <h1> Editer ton potin !</h1>

      <%= form_for @gossip do |f| %>
        <div class="form-group">   
            <%= f.text_field :title, class:'form_control' %>
            <%= label_tag 'Le titre' %>
        </div>
        <div class="form-group"> 
            <%= f.text_field :content, class:'form_control' %>
            <%= label_tag 'Allez modifie' %>
        </div>  
        <div class="form-group">
        <%= submit_tag "Modifier", class: 'btn btn-primary btn-lg btn-submit'  %>
      <% end %>
    </div>
  </body>
</html>

app/views/gossips/index.html.erb
<html>
	<header>
		<div class="container">
      		<%= flash_messages %> <!-- voir applicaiton helper-->
      		<%= yield %>
    	</div>
	</header>
	<body>
		<h1 class ="ml-3 mt-3">Bienvenue sur le site des potins</h1>
		<div class="card-deck">
		<% Gossip.all.to_a.each do |gsp| %>
				<div class="col-sm-4 mb-3">
					<div class="card">
  						<div class="card-header"> <%= gsp.title %></div> 
		   		<!-- div class="card border-primary mb-3 ml-3" style="max-width: 18rem;">
		  			<div class="card-header"> <%= gsp.title %></div> -->
		  				<div class="card-body text-secondary">
		    				<h5 class="card-title">L'auteur: <%= User.find(gsp.user_id).first_name %></h5>
		    				<p class="card-text">Le lien: <%= link_to "ici", gossip_path(gsp.id) %></p>
							<h5> <%= gsp.comments.size %> commentaires </h5>
		    				<% if current_user %>
			    				<% if gsp.user_id == current_user.id %>
				    				<div class="btn btn-primary"> 
				    					<%= link_to "Modifier", edit_gossip_path(gsp.id), :class => "text-white"%>
				    				</div>
				    				<div class="btn btn-danger"> 
				    					<%= link_to "Supprimer", gossip_path(gsp.id),method: :delete, data: {confirm: "Etes vous sûr?"}, :class => "text-white"%>
				    				</div>

				    			<% end %>
				    		<% end %>
							
								<% if current_user %>
									 	<% @like = Like.find_by(user_id:current_user.id, gossip_id:gsp.id)%>
         								<% if @like == nil %>
											<div class="btn btn-primary"> 
								        			<%= link_to "Like", gossip_like_index_path(gsp.id),method: :post, :class => "text-white"%> 
									        </div>
										<% else %>
												<div class="btn btn-outline-primary"> 
								        			<%= link_to "Unlike", gossip_like_path(gsp.id, @like.id),method: :delete%> 
									        	</div>
										<% end %>
									
								<% else %>
									<div class="btn btn-primary"> 
								        <%= link_to "Like", gossip_like_index_path(gsp.id),method: :post, :class => "text-white"%> 
									</div>
								<% end %> 	
								<%= gsp.likes.size %> like(s)
							</div>
		  				</div>
				</div>
		<% end %>
	</div>
	</body>
</html>

app/views/gossips/new.html.erb
<html>
  <body>
    <div class="container">
      <%= flash_messages %> <!-- voir applicaiton helper-->
      <%= yield %>
    </div>
    
    <div class="container">
      <h1> Créer ton nouveau potin !</h1>
      <%= form_tag url_for(action: 'create'), method: "post" do %>
        <input type="hidden" name="authenticity_token" value= <%= form_authenticity_token %> >
        <br /> 
          <%= text_field_tag 'gossip_title' %>
          <%= label_tag 'Le titre' %>
        <br /> 
          <%= text_area_tag 'gossip_content'%>
          <%= label_tag 'Dis nous tout' %>
        <br /> <br />
        <%= submit_tag "Valider", class: 'btn btn-primary btn-lg btn-submit'  %>
      <% end %>
    </div>
  </body>
</html>

app/views/gossips/show.html.erb
<html>
  <body>
  	<div class="container">
      <%= flash_messages %> <!-- voir applicaiton helper-->
      <%= yield %>
    </div>

	<h1 class ="ml-3 mt-3">Gossip n°<%= params[:id].to_i %></h1>
	<div class="container">
		<h3>Ces informations</h3>
			<div class="row">
    			<div class="col">
      				L'auteur:
    			</div>
    			<div class="col">
      			<%= User.find(@gossip.user_id).first_name %> <%= User.find(@gossip.user_id).last_name %> <%= link_to "Plus d'infos sur l'auteur", author_path(@gossip.user_id) %>
    			</div>
  			</div>
  			<div class="row">
    			<div class="col">
      				La ville de l'auteur :
    			</div>
    			<div class="col">
      				<%= City.find(User.find(@gossip.user_id).city_id).name %>
			<%= link_to "Plus d'infos sur la ville", city_path(User.find(@gossip.user_id).city_id) %>
    			</div>
  			</div>
  			<div class="row">
    			<div class="col">
      				Le titre :
    			</div>
    			<div class="col">
      				<%= @gossip.title %>
    			</div>
  			</div>
  			<div class="row">
    			<div class="col">
      				Le contenu :
    			</div>
    			<div class="col">
      				<%= @gossip.content %>
    			</div>
  			</div>
			<div class="row">
    			<div class="col">
      				Créé le: <%= (@gossip.created_at).to_date %>
    			</div>
    			<div class="col">
      				Updaté le: <%= (@gossip.updated_at).to_date %>
    			</div>
  			</div>
	</div>
	<div class="container">
								<% if current_user %>
									 	<% @like = Like.find_by(user_id:current_user.id, gossip_id:@gossip.id)%>
         								<% if @like == nil %>
											<div class="btn btn-primary"> 
								        			<%= link_to "Like", gossip_like_index_path(@gossip.id),method: :post, :class => "text-white"%> 
									        </div>
										<% else %>
												<div class="btn btn-outline-primary"> 
								        			<%= link_to "Unlike", gossip_like_path(@gossip.id, @like.id),method: :delete%> 
									        	</div>
										<% end %>
									
								<% else %>
										<div class="btn btn-primary"> 
								        	<%= link_to "Like", gossip_like_index_path(@gossip.id),method: :post, :class => "text-white"%> 
									    </div>
								<% end %> 	
								<span class="badge badge-secondary"><%= @gossip.likes.size %> </span> like(s)
								<br /> 
								<br /> 
	</div>
	<div class="container">
		<h3>Ces commentaires</h3>
		<div id="list-example" class="list-group">
		<% for comment in @gossip.comments %>
      			<h5 class="list-group-item list-group-item-action"><%= User.find(comment.user_id).first_name %> 
      				<%= User.find(comment.user_id).last_name %>
      				:
      				<%= comment.content %>
      				</h5>
      			
      			<% if current_user %>
	      			<% if comment.user_id == current_user.id %>
		      			<div class="btn btn-primary"> 
				    		<%= link_to "Modifier", edit_gossip_comment_path(@gossip.id, comment.id), :class => " text-white" %>
				    	</div>
				    	<div class="btn btn-danger"> 
				    		<%= link_to "Supprimer", gossip_comment_path(@gossip.id, comment.id),method: :delete, data: {confirm: "Etes vous sûr?"}, :class => "text-white"%> <!-- pas de bon lien -->
				    	</div>
			    	<br />
			    	<% end %>
			    <% end %>
		<% end %>
		<h5> <span class="badge badge-secondary"><%= @gossip.comments.size %> </span> commentaire(s) </h5>
		<br /> <br /> 
	</div>
<br /> <br /> 
	<div class="container">
		<h3>Nouveau commentaire?</h3>
			<%= form_tag gossip_comments_path(@gossip.id), method: :post do %>
	        	<input type="hidden" name="authenticity_token" value= <%= form_authenticity_token %> >
	        	<input type="hidden" name="gossip_id" value= <%= @gossip.id %> > 
	          	<%= text_area_tag 'comment_content' %> <br />
	        	<br /> 
	        	<%= submit_tag "Envoyer", class: 'btn btn-primary btn-lg btn-submit'  %>
			<% end %>
	</div>
  </body>
</html>
	