config/routes.rb
Rails.application.routes.draw do
  resources :gossips do
    resources :like, only: [:index, :create, :destroy]
  end
  resources :gossips do
    resources :comments
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :authors, only: [:show, :create, :new]
  resources :cities, only: [:show]
  resources :team, only: [:index]
  resources :contact, only: [:index]
  resources :welcome, only: [:index, :show]
  root to: 'gossips#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	validates :name,
	  presence: true,
	  uniqueness: true #une ville n'a pas le meme nom en fr
	validates :zip_code,
	  presence: true,
	  format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "please enter a valid french zip code" } 
	has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
	validates :content,
	  presence: true
	belongs_to :user		#Comment en relation N-1 avec user et gossip 
	belongs_to :gossip
	
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	validates :title, 
	  presence: true,
	  length: { in: 3..14, wrong_length: "3 to 14 characters is allowed" }
	validates :content,
	  presence: true,
	  length: { minimum: 50, too_short: "50 characters is the minimum allowed" }
	
	belongs_to :user
	has_many :comments
	has_many :join_tag_gossips
	has_many :tags, through: :join_tag_gossips
	has_many :likes

end

app/models/join_pm.rb
class JoinPm < ApplicationRecord
	validates :user_id,
	    presence: true,
	    numericality: { only_integer: true, greater_than_or_equal_to: 1}
	validates :private_message_id,
	    presence: true,
	    numericality: { only_integer: true, greater_than_or_equal_to: 1}
	    
	belongs_to :user
	belongs_to :private_message
end

app/models/join_tag_gossip.rb
class JoinTagGossip < ApplicationRecord
	validates :tag_id,
	    presence: true,
	    numericality: { only_integer: true, greater_than_or_equal_to: 1}
	validates :gossip_id,
	    presence: true,
	    numericality: { only_integer: true, greater_than_or_equal_to: 1}
	belongs_to :tag 
	belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
	validate :unique_like

	belongs_to :user
	belongs_to :gossip

	def unique_like
		if User.find(user_id).unique(gossip_id)
			errors.add(:gossip_id, "déjà fait") 
		end
	end
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	  validates :content,
	    presence: true
	  
	  belongs_to :user
	  has_many :join_pms
	  has_many :users, through: :join_pms
      
end

app/models/tag.rb
class Tag < ApplicationRecord
	validates :title, 
	  presence: true,
	  length: { in: 3..14, wrong_length: "3 to 14 characters is allowed" }
	  
	has_many :join_tag_gossips
	has_many :gossips, through: :join_tag_gossips
end

app/models/user.rb
class User < ApplicationRecord
	validates :email,
      presence: true, #tjr rempli
      uniqueness: true,  #unique
      format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" } #format
    validates :first_name,
      presence: true
    validates :last_name,
      presence: true
    validates :description,
      presence: true,
      length: { minimum: 50, too_short: "50 characters is the minimum allowed" }
    validates :age,
      presence: true,
      numericality: { only_integer: true, greater_than_or_equal_to: 1}
    validates :password, 
      presence: true, 
      length: { minimum: 6 }
      
    has_secure_password
	belongs_to :city
	has_many :gossips
	has_many :private_messages
	has_many :join_pms
	has_many :likes
 
 	def unique(gsp_id)
 		
 		self.likes.map{|like| like.gossip_id}.include?(gsp_id)
 		
 	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_class_for flash_type
        { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }.stringify_keys[flash_type.to_s] || flash_type.to_s
    end
    
    def flash_messages(opts = {})
        flash.each do |msg_type, message|
          concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}", role: "alert") do 
                  concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
                  concat message 
                end)
        end
        nil
    end

    def current_user
    	User.find_by(id: session[:user_id])
	end

	def log_in(user)
    	session[:user_id] = user.id
  	end

  	def logged_in?
  		session[:user_id]
  	end

end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
    	session[:user_id] = user.id
  	end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/show.html.erb
<h1 class ="ml-3">Bienvenue sur le site des potins</h1>
  
<% Gossip.all.to_a.each do |gsp| %>  
   	
   		<div class="card border-primary mb-3 ml-3" style="max-width: 18rem;">
  			<div class="card-header"> <%= gsp.title %></div>
  				<div class="card-body text-secondary">
    				<h5 class="card-title">L'auteur: <%= User.find(gsp.user_id).first_name %></h5>
    				<p class="card-text">Le lien: <%= link_to "ici", gossips_id_path(gsp.id) %></p>
  				</div>
		</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
        <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>
  <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <div class="collapse navbar-collapse" id="navbarSupportedContent"> 
            <%= link_to "The Gossip Project", welcome_index_path, :class => "text-white"  %> 
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>         
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <div class="nav-link"> <%= link_to "La liste", gossips_path, :class => "text-white" %> </div>
              </li>
              <li class="nav-item">
                  <div class="nav-link"> <%= link_to "Créer un gossip", new_gossip_path, :class => "text-white" %> </div>
              </li>
              <li class="nav-item">
                <div class="nav-link"> <%= link_to "Team", team_index_path, :class => "text-white" %> </div>
              </li>
              <li class="nav-item">
                <div class="nav-link"> <%= link_to "Contact", contact_index_path, :class => "text-white" %> </div>
              </li>
            </ul>
            </div>
              <!-- -->
            <div  class="collapse navbar-collapse justify-content-end">
                <% unless current_user %>
                  <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      S'inscrire/Se connecter
                      </a>
                      <div class="dropdown-menu dropdown-menu-right animate slideIn" aria-labelledby="navbarDropdown">
                        <div class="dropdown-item"> <%= link_to "S'enregistrer", new_author_path %> </div>
                        <div class="dropdown-item"> <%= link_to "Se connecter", new_session_path %> </div>
                      </div>
                    </li>
                  </ul>
                <% else %>
                    <div class="nav-link"> <%= link_to "Mon Profil", author_path(current_user), :class => "text-white" %> </div>
                    <div class="nav-link"> <%= link_to "Se déconnecter", session_path(session.id), method: :delete, :class => "text-white" %> </div> 
                <% end %>
        </nav>
  </header>

  <body>
    <%= yield %>
  </body>
</html>